version: '3.8'

services:
  app:
    image: ghcr.io/tomacheese/watch-follow-follower:latest
    volumes:
      - type: bind
        source: ./data
        target: /data/
    init: true
    restart: always